RomanLegion\GameBundle\Entity\Account:
    properties:
        username:
            - NotBlank: ~
            - Length:
              min: 5
              max: 30
        displayName:
            - NotBlank: ~
            - Length:
              min: 5
              max: 40
        password:
            - NotBlank: ~
            - Length:
              min: 8
        banned:
            - NotNull: ~
            - Type:
              type: bool